# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branch:
      - test
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup VCPKG
      run: |
        git clone https://github.com/NordicPlayground/vcpkg.git
        cd vcpkg
        sh ./bootstrap-vcpkg.sh
        vcpkg install nrf-ble-driver
        cd ..

    - name: Run a multi-line script
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install -r requirements-dev.txt
        python3 setup.py bdist_wheel --build-type Release
